### ISSUE TITLE
FontManager.getFont("方正黑体");这个方法返回值为null 

### ISSUE THREAD

**Issue by qiyunfei** [alibaba/simpleimage#15]
这个我是测试给图片添加文字水印的时候测试发现的 ，空指针，原因是创建FootnoteDrawTextItem对象时没有指定字体，而源码使用的是默认字体FontManager.getFont("方正黑体"); 这个返回的是空，又去看了FontManager源码，发现cache这个没有是个空map 然后有个 静态块，感觉是这里加载的，但是没有写实现
大概看了下FontManager这块的源码，
com.alibaba.simpleimage.SimpleImageException: java.lang.NullPointerException
	at com.alibaba.simpleimage.render.WriteRender.render(WriteRender.java:218)
	at com.mljr.carrier.test.SimpleImageDemo.doDrawImageText(SimpleImageDemo.java:326)
	at com.mljr.carrier.test.SimpleImageDemo.testFootnoteDrawTextItem(SimpleImageDemo.java:291)
	at com.mljr.carrier.test.SimpleImageDemo.main(SimpleImageDemo.java:297)
Caused by: java.lang.NullPointerException
	at com.alibaba.simpleimage.render.FootnoteDrawTextItem.drawText(FootnoteDrawTextItem.java:110)
	at com.alibaba.simpleimage.util.ImageDrawHelper.drawText(ImageDrawHelper.java:54)
	at com.alibaba.simpleimage.render.DrawTextRender.render(DrawTextRender.java:80)
	at com.alibaba.simpleimage.render.WriteRender.render(WriteRender.java:213)

**Comment by axmanwang** [comment]
你的系统中是否安装了这个字体，这是java原生API,如果返回空，那只能是系统未安装该字体。

**Comment by axmanwang** [comment]
是否是系统平台问题，以及jdk版本，如果是windows，用win32FontManager,或
FontManagerFactory.getInstance()
另外你的系统中是否安装了这个字体。
